import 'package:sakinah_app/features/azkar/domain/entities/azkar.dart';

class AzkarModel extends Azkar {
  final String? supabaseId; // UUID from Supabase
  final bool isFavorite;
  final DateTime? updatedAt;

  const AzkarModel({
    super.id,
    this.supabaseId,
    required super.arabicText,
    super.transliteration,
    super.translation,
    required super.category,
    required super.associatedMoods,
    super.repetitions = 1,
    super.createdAt,
    super.isCustom = false,
    this.isFavorite = false,
    this.updatedAt,
  });

  factory AzkarModel.fromJson(Map<String, dynamic> json) {
    return AzkarModel(
      id: null, // We'll use supabaseId for cloud storage
      supabaseId: json['id'] as String?,
      arabicText: json['arabic_text'] as String,
      transliteration: json['transliteration'] as String?,
      translation: json['translation'] as String?,
      category: json['category'] as String,
      associatedMoods: json['associated_moods'] != null
          ? List<String>.from(json['associated_moods'] as List)
          : <String>[],
      repetitions: json['repetitions'] as int? ?? 1,
      isFavorite: json['is_favorite'] as bool? ?? false,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : null,
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'] as String)
          : null,
      isCustom: true, // Supabase azkar are custom by default
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': supabaseId,
      'arabic_text': arabicText,
      'transliteration': transliteration,
      'translation': translation,
      'category': category,
      'associated_moods': associatedMoods,
      'repetitions': repetitions,
      'is_favorite': isFavorite,
      'created_at': createdAt?.toIso8601String(),
      'updated_at': updatedAt?.toIso8601String(),
    };
  }

  Map<String, dynamic> toSupabaseInsert() {
    final json = toJson();
    // Remove fields that are auto-generated by Supabase
    json.remove('id');
    json.remove('created_at');
    json.remove('updated_at');
    return json;
  }

  @override
  Azkar copyWith({
    int? id,
    String? arabicText,
    String? transliteration,
    String? translation,
    String? category,
    List<String>? associatedMoods,
    int? repetitions,
    DateTime? createdAt,
    bool? isCustom,
  }) {
    return AzkarModel(
      id: id ?? this.id,
      supabaseId: supabaseId,
      arabicText: arabicText ?? this.arabicText,
      transliteration: transliteration ?? this.transliteration,
      translation: translation ?? this.translation,
      category: category ?? this.category,
      associatedMoods: associatedMoods ?? this.associatedMoods,
      repetitions: repetitions ?? this.repetitions,
      createdAt: createdAt ?? this.createdAt,
      isCustom: isCustom ?? this.isCustom,
      isFavorite: isFavorite,
      updatedAt: updatedAt,
    );
  }

  AzkarModel copyWithSupabase({
    String? supabaseId,
    String? arabicText,
    String? transliteration,
    String? translation,
    String? category,
    List<String>? associatedMoods,
    int? repetitions,
    bool? isFavorite,
    DateTime? createdAt,
    DateTime? updatedAt,
    bool? isCustom,
  }) {
    return AzkarModel(
      id: id,
      supabaseId: supabaseId ?? this.supabaseId,
      arabicText: arabicText ?? this.arabicText,
      transliteration: transliteration ?? this.transliteration,
      translation: translation ?? this.translation,
      category: category ?? this.category,
      associatedMoods: associatedMoods ?? this.associatedMoods,
      repetitions: repetitions ?? this.repetitions,
      isFavorite: isFavorite ?? this.isFavorite,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      isCustom: isCustom ?? this.isCustom,
    );
  }
}
